#!/bin/sh

if [ "$#" -ne "4" ]
then
	cat <<-tac
		USAGE: $0 <outfile> <min> <step> <max>
		where <min>, <step>, and <max> are libset counts
	tac
	exit 1
fi
outfile="$1"
min="$2"
step="$3"
max="$4"

for libsets in `seq "$min" "$step" "$max"`
do
	printf "%s" "$libsets" | tee -a "$outfile"
	for command in "./perfect" "LD_PRELOAD=../tlsblock/libtlsblock.so ./perfect"
	do
		printf ",%s" "`eval $command "$libsets" | cut -d" " -f1`" | tee -a "$outfile"
	done
	echo | tee -a "$outfile"
done
