#!/bin/sh

if [ "$#" -lt "4" ]
then
	cat <<-tac
		USAGE: $0 <outfile> <min> <step> <max> [cmdline]...
		where <min>, <step>, and <max> are libset counts
	tac
	exit 1
fi
outfile="$1"
min="$2"
step="$3"
max="$4"
shift 4

for libsets in `seq "$min" "$step" "$max"`
do
	printf "%s" "$libsets" | tee -a "$outfile"
	for command in "./perfect" "LD_PRELOAD=../tlsblock/libtlsblock.so ./perfect"
	do
		measurement="`eval $command "$libsets" $*`"
		case "$measurement" in
		*μs*)
			printf ",%s" "`echo "$measurement" | cut -d" " -f1`" | tee -a "$outfile"
			;;
		*ns*)
			printf ",%s" "`echo "$measurement" | tr -d , | sed -n 's|[^0-9]*\([0-9]\+\) ns/iter (+/- \([0-9]\+\)).*|\1,\2|p'`" | tee -a "$outfile"
			;;
		*)
			printf "%s\n" "UNPARSEABLE OUTPUT:" "$measurement" >&2
			exit 1
			;;
		esac
	done
	echo | tee -a "$outfile"
done
