#!/bin/sh

if [ "$#" -eq "0" ]
then
	echo "USAGE: $0 <libsets> [cmdline]..."
	exit 1
fi

groups="$1"
shift 1
script="perf"
if [ "$#" -ne "0" ]
then
	script="$*"
fi

if [ -n "$LD_PRELOAD" ]
then
	LD_PRELOAD=":$LD_PRELOAD"
fi

LD_PRELOAD="`echo libinger/target/*/libinger.so`$LD_PRELOAD" LIBGOTCHA_NUMGROUPS="$groups" LIBGOTCHA_NOGLOBALS= exec ./$script
