#!/bin/sh

if [ "$#" -eq "0" ]
then
	echo "USAGE: $0 <libsets> [cmdline]..."
	exit 1
fi

groups="$1"
shift 1
script="perf"
if [ "$#" -ne "0" ]
then
	script="$*"
fi

LD_PRELOAD=libinger/target/release/libinger.so LIBGOTCHA_NUMGROUPS="$groups" LIBGOTCHA_NOGLOBALS= exec ./$script
