#!/bin/sh

if [ "$#" -eq "0" ]
then
	echo "USAGE: $0 <cmdline>..."
	exit 1
fi

if [ -n "$LD_PRELOAD" ]
then
	LD_PRELOAD=":$LD_PRELOAD"
fi

LD_PRELOAD="`dirname "$0"`/libltrace.so$LD_PRELOAD" exec "$@"
