starti
watch _rtld_global._dl_rtld_lock_recursive
#watch _rtld_global._dl_rtld_unlock_recursive
#watch _rtld_global._dl_load_lock
watch _rtld_global._dl_make_stack_executable_hook
watch _rtld_global._dl_init_static_tls
watch _rtld_global._dl_wait_lookup_done
